<?php

namespace Container3xZRNLD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdmin2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BJ9wYPE.App\Entity\Admin' shared service.
     *
     * @return \App\Entity\Admin
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BJ9wYPE": it references class "App\\Entity\\Admin" but no such service exists.');
    }
}
