<?php

namespace Container3xZRNLD;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDonateurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BjCq.sz.App\Entity\Donateur' shared service.
     *
     * @return \App\Entity\Donateur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BjCq.sz": it references class "App\\Entity\\Donateur" but no such service exists.');
    }
}
