<?php

namespace ContainerW6OacqJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TZEYeMJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tZEYeMJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tZEYeMJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'donateurRepository' => ['privates', 'App\\Repository\\DonateurRepository', 'getDonateurRepositoryService', true],
        ], [
            'donateurRepository' => 'App\\Repository\\DonateurRepository',
        ]);
    }
}
