<?php

namespace ContainerW6OacqJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OEHstk4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OEHstk4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OEHstk4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'maisonDeCulte' => ['privates', '.errored..service_locator.OEHstk4.App\\Entity\\MaisonDeCulte', NULL, 'Cannot autowire service ".service_locator.OEHstk4": it references class "App\\Entity\\MaisonDeCulte" but no such service exists.'],
        ], [
            'maisonDeCulte' => 'App\\Entity\\MaisonDeCulte',
        ]);
    }
}
