<?php

namespace ContainerW6OacqJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProjet2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QDkw4M0.App\Entity\Projet' shared service.
     *
     * @return \App\Entity\Projet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.QDkw4M0": it references class "App\\Entity\\Projet" but no such service exists.');
    }
}
