<?php

namespace ContainerXR7CHOJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QDkw4M0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QDkw4M0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QDkw4M0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'projet' => ['privates', '.errored..service_locator.QDkw4M0.App\\Entity\\Projet', NULL, 'Cannot autowire service ".service_locator.QDkw4M0": it references class "App\\Entity\\Projet" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'projet' => 'App\\Entity\\Projet',
        ]);
    }
}
