<?php

namespace ContainerXR7CHOJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDonateur2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IYr2fLk.App\Entity\Donateur' shared service.
     *
     * @return \App\Entity\Donateur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IYr2fLk": it references class "App\\Entity\\Donateur" but no such service exists.');
    }
}
