<?php

namespace ContainerXR7CHOJ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaisonDeCulte2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S4EqzCz.App\Entity\MaisonDeCulte' shared service.
     *
     * @return \App\Entity\MaisonDeCulte
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.S4EqzCz": it references class "App\\Entity\\MaisonDeCulte" but no such service exists.');
    }
}
