<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXR7CHOJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXR7CHOJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXR7CHOJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXR7CHOJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXR7CHOJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'XR7CHOJ',
    'container.build_id' => '88b77d88',
    'container.build_time' => 1692188011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXR7CHOJ');
