<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ2xkxfX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ2xkxfX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ2xkxfX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ2xkxfX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ2xkxfX\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z2xkxfX',
    'container.build_id' => '5dee7245',
    'container.build_time' => 1691345303,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ2xkxfX');
