<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3xZRNLD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3xZRNLD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3xZRNLD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3xZRNLD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3xZRNLD\App_KernelDevDebugContainer([
    'container.build_hash' => '3xZRNLD',
    'container.build_id' => '729835bf',
    'container.build_time' => 1691852041,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3xZRNLD');
